#!/bin/bash

# Get the CPU temperature

temp=0
num_cores=$(nproc)
real_cores=0

for (( i=0; i<$num_cores; i++ )); do
    core_temp=$(sensors | awk "/^Core $i/ {printf(\"%.1f\n\", \$3)}")
    if [ -n "$core_temp" ]; then
        temp=$(echo "$temp+$core_temp" | bc)
        real_cores=$((real_cores+1))
    fi
done

cpu_temp=$(printf "%.0f" $(echo "scale=1; $temp/$real_cores" | bc))

# Print the CPU temperature
echo "$cpu_temp"

